// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: AirQualityMonitor

#include "../ui.h"
#include <stdio.h>

/// @brief callback function for drawing the graph
/// @param e 
static void draw_event_cb(lv_event_t * e)
{
    lv_obj_draw_part_dsc_t * dsc = lv_event_get_draw_part_dsc(e);
    // copy draw context
    memcpy(GetDrawCtx(), dsc->draw_ctx, sizeof(lv_draw_ctx_t));
    if ( dsc == NULL)
    {
        return;
    }
    // printf("dsc->part = %lu\n", dsc->part);
    if(dsc->part == LV_PART_ITEMS) {
        lv_obj_t * obj = lv_event_get_target(e);
        lv_chart_series_t * ser = lv_chart_get_series_next(obj, NULL);
        uint32_t cnt = lv_chart_get_point_count(obj);
        /*Make older value more transparent*/
        // dsc->rect_dsc->bg_opa = (LV_OPA_COVER *  dsc->id) / (cnt - 1);
        dsc->rect_dsc->bg_opa = LV_OPA_COVER;
        
        /*Make smaller values blue, higher values red*/
        // lv_coord_t * x_array = lv_chart_get_x_array(obj, ser);
        lv_coord_t * y_array = lv_chart_get_y_array(obj, ser);
        /*dsc->id is the tells drawing order, but we need the ID of the point being drawn.*/
        uint32_t start_point = lv_chart_get_x_start_point(obj, ser);
        uint32_t p_act = (start_point + dsc->id) % cnt; /*Consider start point to get the index of the array*/
        lv_opa_t y_opa = (y_array[p_act] * LV_OPA_50) / 500;

        dsc->rect_dsc->bg_color = lv_color_mix(lv_palette_main(LV_PALETTE_RED),
                                                lv_palette_main(LV_PALETTE_BLUE),
                                                y_opa);
    }
}

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AirQualityChart = lv_chart_create(ui_Screen1);
    lv_obj_set_width(ui_AirQualityChart, 593);
    lv_obj_set_height(ui_AirQualityChart, 317);
    lv_obj_set_x(ui_AirQualityChart, 9);
    lv_obj_set_y(ui_AirQualityChart, -11);
    lv_obj_set_align(ui_AirQualityChart, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_AirQualityChart, draw_event_cb, LV_EVENT_DRAW_PART_BEGIN, NULL);
    lv_obj_set_style_line_width(ui_AirQualityChart, 0, LV_PART_ITEMS);   /*Remove the lines*/
    lv_chart_set_type(ui_AirQualityChart, LV_CHART_TYPE_SCATTER);

    lv_chart_set_axis_tick(ui_AirQualityChart, LV_CHART_AXIS_PRIMARY_X, 10, 5, 5, 6, false, 50);
    lv_chart_set_axis_tick(ui_AirQualityChart, LV_CHART_AXIS_PRIMARY_Y, 10, 5, 6, 2, true, 50);
    lv_chart_set_div_line_count(ui_AirQualityChart, 6, 5);
        
    lv_chart_set_range(ui_AirQualityChart, LV_CHART_AXIS_PRIMARY_X, 0, XAXIS_PTS);
    lv_chart_set_range(ui_AirQualityChart, LV_CHART_AXIS_PRIMARY_Y, 0, 500);
    lv_chart_set_point_count(ui_AirQualityChart, DATA_BUFSIZE);
    lv_chart_add_series(ui_AirQualityChart, lv_palette_main(LV_PALETTE_RED), LV_CHART_AXIS_PRIMARY_Y);
       
    ui_GraphTitle = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_GraphTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GraphTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_GraphTitle, -1);
    lv_obj_set_y(ui_GraphTitle, -204);
    lv_obj_set_align(ui_GraphTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GraphTitle, "Air Quality vs Time");
    lv_obj_set_style_text_font(ui_GraphTitle, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_vocindex_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, -365);
    lv_obj_set_y(ui_Image1, -15);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SettingsButton, 140);
    lv_obj_set_height(ui_SettingsButton, 50);
    lv_obj_set_x(ui_SettingsButton, 304);
    lv_obj_set_y(ui_SettingsButton, -204);
    lv_obj_set_align(ui_SettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SettingsLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SettingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SettingsLabel, 307);
    lv_obj_set_y(ui_SettingsLabel, -203);
    lv_obj_set_align(ui_SettingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsLabel, "Settings");
    lv_obj_set_style_text_color(ui_SettingsLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SettingsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SettingsLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_XLabel0 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_XLabel0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XLabel0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XLabel0, -270);
    lv_obj_set_y(ui_XLabel0, 190);
    lv_obj_set_align(ui_XLabel0, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel0, "Jan-01\n00:00:00");
 
    ui_XLabel1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_XLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XLabel1, -129);
    lv_obj_set_y(ui_XLabel1, 190);
    lv_obj_set_align(ui_XLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel1, "Jan-01\n06:00:00");
 
    ui_XLabel2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_XLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XLabel2, 14);
    lv_obj_set_y(ui_XLabel2, 190);
    lv_obj_set_align(ui_XLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel2, "Jan-01\n12:00:00");
    
    ui_XLabel3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_XLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XLabel3, 155);
    lv_obj_set_y(ui_XLabel3, 190);
    lv_obj_set_align(ui_XLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel3, "Jan-01\n18:00:00");
    
    ui_XLabel4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_XLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XLabel4, 299);
    lv_obj_set_y(ui_XLabel4, 190);
    lv_obj_set_align(ui_XLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_XLabel4, "Jan-02\n00:00:00");
    
    lv_obj_add_event_cb(ui_SettingsButton, ui_event_SettingsButton, LV_EVENT_ALL, NULL);

}
